// Generated by view binder compiler. Do not edit!
package com.example.androidprojecta.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.androidprojecta.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActorsListItemBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final ImageView imageViewContact;

  @NonNull
  public final CardView parent;

  @NonNull
  public final TextView txtDescription;

  @NonNull
  public final TextView txtName;

  private ActorsListItemBinding(@NonNull CardView rootView, @NonNull ImageView imageViewContact,
      @NonNull CardView parent, @NonNull TextView txtDescription, @NonNull TextView txtName) {
    this.rootView = rootView;
    this.imageViewContact = imageViewContact;
    this.parent = parent;
    this.txtDescription = txtDescription;
    this.txtName = txtName;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActorsListItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActorsListItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.actors_list_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActorsListItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageViewContact;
      ImageView imageViewContact = ViewBindings.findChildViewById(rootView, id);
      if (imageViewContact == null) {
        break missingId;
      }

      CardView parent = (CardView) rootView;

      id = R.id.txtDescription;
      TextView txtDescription = ViewBindings.findChildViewById(rootView, id);
      if (txtDescription == null) {
        break missingId;
      }

      id = R.id.txtName;
      TextView txtName = ViewBindings.findChildViewById(rootView, id);
      if (txtName == null) {
        break missingId;
      }

      return new ActorsListItemBinding((CardView) rootView, imageViewContact, parent,
          txtDescription, txtName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
